# Generated by Django 5.2.4 on 2026-05-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_message_file_alter_message_content_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_text',
            field=models.CharField(default='Hey there! I am using .connect', max_length=100),
        ),
    ]
